require('lze').load {
  {
    'copilot.lua',
    event = 'InsertEnter',
    cmd = 'Copilot',
    after = function(_)
      require('copilot').setup {
        panel = { enabled = false },
        copilot_model = 'gpt-4.1',
        suggestion = {
          enabled = true,
          auto_trigger = true,
          hide_during_completion = true,
          keymap = {
            accept = '<Tab>',
            accept_word = '<C-k>',
            accept_line = '<C-l>',
            next = '<M-]>',
            prev = '<M-[>',
            dismiss = '<C-]>',
          },
        },
        filetypes = {
          -- Disable for Windsurf languages
          python = false,
          ruby = false,
          elixir = false,
          rust = false,
          typescript = false,
          javascript = false,
          javascriptreact = false,
          typescriptreact = false,
          -- Disable for Windsurf languages
          lua = false,
          go = true,
          nix = true,
          c = true,
          cpp = true,
          java = true,
          php = true,
          html = true,
          css = true,
          scss = true,
          vue = true,
          svelte = true,
          bash = true,
          zsh = true,
          fish = true,
          json = true,
          yaml = true,
          toml = true,
          markdown = true,
          gitrebase = true,
          gitcommit = true,
          -- Disable for specific contexts
          ['grug-far'] = false,
          ['grug-far-history'] = false,
          ['grug-far-help'] = false,
          ['.'] = false,
          [''] = false,
          ['chatgpt-input'] = false,
          oil = false,
          minifiles = false,
        },
      }
    end,
  },
}
